FROM maven:3.6.3-jdk-11 as maven
COPY ./ ./maven-app
WORKDIR /maven-app 
RUN mvn install
FROM openjdk:11
WORKDIR /maven-app
COPY --from=maven /maven-app/target/*.jar ./app.jar 
ENTRYPOINT ["java","-jar","./app.jar"]
